### ISSUE TITLE
List keys only

### ISSUE THREAD

**Issue by gilles6** [rogervila/array-diff-multidimensional#15]
It would be interesting to have an option to get an arrays of keys only, maybe like: `['a', 'c.f']`.

**Comment by rogervila** [comment]
Hey, thank you for the feedback!

Could you provide a more detailed example?

**Comment by gilles6** [comment]
For instance, the difference between these two arrays...
`$array1`:
``` 
[
  'a' => 'Barbapapa',
  'b' => 'Barbouille',
  'c' => [
    'foo' => 'Barbamama'
  ],
  'd' => 'Barbabelle'
];
```
`$array2`:
```
[
  'a' => 'Barbapapa',
  'b' => 'Barbotine',
  'c' => [
    'foo' => 'Barbamama',
    'bar' => 'Barbidur'
  ]
]
```
...would return:
`['b', 'c.bar', 'd']`

**Comment by rogervila** [comment]
Let me give it a thought on which would be the better way to achieve it in terms of performance.

**Comment by rogervila** [comment]
Hi @gilles6 

I have found [this package](https://github.com/adbario/php-dot-notation) that accomplishes exactly what you need.

```php
$data = [
    'a' => [
        'b' => 'c',
        'd' => 'e',
    ],
    'f' => 'g',
];

$dot = new \Adbar\Dot($data);

var_dump($dot->flatten());

/*
array(3) {
  ["a.b"]=>
  string(1) "c"
  ["a.d"]=>
  string(1) "e"
  ["f"]=>
  string(1) "g"
}
*/
```

Thank you.
